backupsDirectory: backups
disableSSLHostnameVerification: false
jobTimeout:
  duration: 1
  unit: HOURS
serviceUrl: http://localhost:8080/api/configuration

#encryption settings.
encryptionEnabled: true
clientEncryptionKeyStore:
  location: enc-default.jceks
  password: changeit
  type: JCEKS
wrapKey:
  alias: default-wrap-key
  password: changeit
macKey:
  alias: default-mac-key
  password: changeit