anypoint:
  apiId: "0000000"

http:
  host: "0.0.0.0"
  port: "8081"

mongodb:
  host: "localhost"
  port: "27017"
  user: ""
  password: ""
  ssl: "false"
  db: "configuration"
  collection:
    configuration: "configuration.coordinates"
    documents: "configuration.documents"